### ISSUE TITLE
多层add的Fragment中每一层都使用了ShadowLayout的话，第二层可能发生抖动，背景和颜色发生穿透

### ISSUE THREAD

**Issue by cocowobo** [lihangleo2/ShadowLayout#100]
1.开启activity，加载一个父fragment，立马再加载一个子fragment，这个子fragment中有个列表使用阴影包裹
2.点击列表，add第二个fragment，列表如果有5个item话，只有最后一个item点击所add的第二个子fragment中的阴影包裹的列表下的背景图发生抖动

https://user-images.githubusercontent.com/19485885/116584021-7eccf480-a949-11eb-9a42-7f04f55849cd.mp4

**Comment by cocowobo** [comment]
奇怪的是，只有第一个fragment的最后一个item点击打开的第二个fragment会导致背景抖动，穿透视图，我已经换了阴影库，问题已经不出现了

**Comment by xiaoxing1992** [comment]
> 奇怪的是，只有第一个fragment的最后一个item点击打开的第二个fragment会导致背景抖动，穿透视图，我已经换了阴影库，问题已经不出现了

请教一下您换个哪个阴影库

**Comment by lihangleo2** [comment]
抱歉，一身投入web前端。我会抽时间解决的。感谢你的issues

**Comment by lihangleo2** [comment]
> > 奇怪的是，只有第一个fragment的最后一个item点击打开的第二个fragment会导致背景抖动，穿透视图，我已经换了阴影库，问题已经不出现了
> 
> 请教一下您换个哪个阴影库

兄弟你也遇到了吗？能加你个好友咨询下吗。？非常感谢

**Comment by lihangleo2** [comment]
我有点不大理解问题描述。你是动态加fragment吗？就目前我遇到的场景，应该不会有出现这种问题啊。首先不是列表使用的阴影控件背景是动态生成的图片，列表里会被复用，在fragment里都是用一个生成一个。且阴影图片都是轻量的。

**Comment by lihangleo2** [comment]
> 奇怪的是，只有第一个fragment的最后一个item点击打开的第二个fragment会导致背景抖动，穿透视图，我已经换了阴影库，问题已经不出现了

兄弟加下我的群209010674， 能否描述详细点，或者你留下联系方式，我联系你。

**Comment by lihangleo2** [comment]
> > 奇怪的是，只有第一个fragment的最后一个item点击打开的第二个fragment会导致背景抖动，穿透视图，我已经换了阴影库，问题已经不出现了
> 
> 请教一下您换个哪个阴影库

兄弟加下我的群209010674， 能否描述详细点，或者你留下联系方式，我联系你。

**Comment by lihangleo2** [comment]
此issues先关闭，如果你回来看到了，请和我联系再打开

**Comment by cocowobo** [comment]
抱歉大佬，才回来，项目时几个月前的了，当时换了阴影库很难用，最后又改回来了，改回来不甘心有bug，就继续找问题所在，最后发现和阴影布局的更换没有关系，而是水波纹布局的问题。第一个frag的list的item的根布局用了        android:background="?attr/selectableItemBackground"
第二个frag的list也是用了        android:background="?attr/selectableItemBackground"
后来我把第一个frag的水波纹换掉了，换成了自定义view水波纹，问题就解决了。
这个bug不时所有机型都出现的，我也忘了是哪个收出现的的不是小米10，就是小米8，手上当时就两个测试机，
都是Android 9.0.，我现在把我代码还原到bug那天的在我的新测试机一加都无法复现问题。
