### ISSUE TITLE
clipChildren不支持

### ISSUE THREAD

**Issue by smin9** [lihangleo2/ShadowLayout#102]
布局中设置了clipChildren，不起效果了

**Comment by lihangleo2** [comment]
兄弟能否描述的更详细点？可以截个图评论下。或者加群：209010674    告诉我。最近一心学习web前端。没有及时回复

**Comment by lihangleo2** [comment]
![github_1](https://user-images.githubusercontent.com/38236349/131608743-899a32b4-a54f-4723-9b1a-81e320a78a01.png)
是生效的。只不过你不能通过子view去控制ShadowLayout的大小了。而是要直接设置ShadowLayout的大小

**Comment by lihangleo2** [comment]
![github_2](https://user-images.githubusercontent.com/38236349/131608927-9e58a580-2d75-4f28-9f2c-d781e96dca80.png)
