### ISSUE TITLE
代码设置stroke

### ISSUE THREAD

**Issue by Jarvis-Lau** [lihangleo2/ShadowLayout#103]
看了一下好像没有代码设置stroke的方法，希望能同步增加，另外感谢大佬分享，谢谢

**Comment by lihangleo2** [comment]
好的。最近一心学习web前端。没有及时回复，抱歉

**Comment by lihangleo2** [comment]
兄弟代码设置stoke有3个方法，你看方法名应该就知道了：setStrokeColor()；setStrokeColorTrue()；setStrokeWidth()。

**Comment by Jarvis-Lau** [comment]
尴尬了，我用的3.0.4，这个方法在3.1.3添加了。。抱歉，再次感谢作者分享😊
