### ISSUE TITLE
单边圆角阴影显示不全

### ISSUE THREAD

**Issue by BreezeAndMoon** [lihangleo2/ShadowLayout#104]
因为旧版不支持设置指定圆角,看到2.1.8支持了,犹豫了下没升2.1.8而是直接升到3.2.0，改了一堆xml属性名,然后我后悔了，单边圆角阴影竟然有问题，左右两边有大块的残缺显示不完整，又测试了下用2.1.8是正常的。所以我又改回了2.1.8。。 代码如下,作者可以试着比较下两个版本区别还是很明显的。
  <com.lihang.ShadowLayout
        android:id="@+id/publish_block"
        android:layout_width="match_parent"
        android:layout_height="53dp"
        app:hl_bottomShow="false"
        app:hl_cornerRadius_leftTop="12dp"
        app:hl_cornerRadius_rigthTop="12dp"
        app:hl_leftShow="false"
        app:hl_shadowColor="#1a606060"
        app:hl_rightShow="false"
        app:hl_shadowLimit="4dp"
        tools:visibility="visible"/>

**Comment by cocowobo** [comment]
同样问题，我也出现了

**Comment by jerry9433** [comment]
同样的问题来的

**Comment by jerry9433** [comment]
还不修复吗

**Comment by lihangleo2** [comment]
好的，最近方向一直在web前端。没有及时回复。最近会抽时间解决的，感谢支持

**Comment by lihangleo2** [comment]
![QQ图片20210803184947](https://user-images.githubusercontent.com/38236349/128004454-f1c1547b-baee-4f5c-a356-3c8e058285c6.png)
兄弟们已经解决。会发布个3.2.1非常抱歉，这么晚回复！~

**Comment by jerry9433** [comment]
大佬辛苦了

**Comment by SelectSex** [comment]
牛批大佬，赶紧升级试试
