### ISSUE TITLE
点击时背景颜色问题

### ISSUE THREAD

**Issue by yoyo89757001** [lihangleo2/ShadowLayout#107]
设置 app:hl_layoutBackground_true；app:hl_shapeMode="ripple" ；颜色透明度小于50%时，比如设置为10%，会 出现颜色不一致情况。点击时，有时候亮有时候暗。

**Comment by yoyo89757001** [comment]
轻触时透明度不起效果。长按时透明度有效果，抬起时透明度不起效果，会出现深色颜色。

**Comment by yoyo89757001** [comment]
<com.lihang.ShadowLayout
                    app:hl_cornerRadius="10dp"
                    app:hl_shadowColor="#1D000000"
                    app:hl_shadowLimit="6dp"
                    app:hl_layoutBackground="#fff"
                    app:hl_layoutBackground_true="#116200EE"
                    app:hl_shadowOffsetX="2dp"
                    app:hl_shadowOffsetY="2dp"
                    app:hl_shapeMode="ripple"
                    android:layout_width="0dp"
                    android:layout_weight="1"
                    android:layout_height="match_parent">

样式设置如上。

**Comment by yoyo89757001** [comment]
麻烦修复一下

**Comment by lihangleo2** [comment]
你说的这个问题，麻烦用demo试试，或者查看下demo情况。ripple是水波纹效果。还有pressed和selected。如果真的如你所说有这个bug，我相信issues早已提出，可能是我还没理解你所说的。能否录制个屏幕让我看看。此issues保留1周，希望看到后回复下我。非常感谢你的支持

**Comment by yoyo89757001** [comment]
![image](https://user-images.githubusercontent.com/31086765/128799137-e1c27950-18d3-4243-aab1-13164ca696a4.png)
比如这里加上透明度以后，点击时是没有透明颜色效果的。还是很深的颜色。但是我需要一个很淡很淡的颜色。而且长按的时候他又有透明度效果，长按他又是个很淡的颜色。所有颜色有点乱了。你可以试下

**Comment by lihangleo2** [comment]
兄弟注意shapeMode =“ripple” 是水波纹。  什么是水波纹？？此issues会被关闭哦。 你去看看系统的水波纹效果就知道了

**Comment by scrylove** [comment]
设置了hl_layoutBackground_true一点作用都没有
