### ISSUE TITLE
使用strokeWith，点击改变strokeWith的宽度时，会出现边缘有background颜色的情况。

### ISSUE THREAD

**Issue by amosxb** [lihangleo2/ShadowLayout#109]
![Screenshot_20210813-180931_SmartLedPro](https://user-images.githubusercontent.com/19277279/129341956-e172e518-0e8f-473d-bdbf-85707198516a.jpg)

**Comment by lihangleo2** [comment]
好的  感谢你的回复。有空我会修复的

**Comment by amosxb** [comment]
嗯，谢谢大神，尽快修复下这个BUG，我在给layoutBackground和layoutBackgroundTrue做动画效果时这个BUG非常明显。

**Comment by lihangleo2** [comment]
兄弟，即将发布3.2.2解决你这个问题。注意查看
