### ISSUE TITLE
select在启动的时候不生效

### ISSUE THREAD

**Issue by StrikeZXA** [lihangleo2/ShadowLayout#112]
例如：在demo中的ShapeActivity的onCreate方法设置
binding.ShadowLayoutImage.setSelected(true)
快速关闭activity，然后重新打开有时不生效，而且出现概率很高，最新版本，能力有限，还请大佬不吝赐教，多谢

**Comment by StrikeZXA** [comment]
现在这样可以解决在acitivy启动时设置默认不生效的问题
findViewById<ShadowLayout>(R.id.slSelectContainer).post {
            findViewById<ShadowLayout>(R.id.slSelectContainer).isSelected = true
        }

**Comment by lihangleo2** [comment]
这个问题很久之前的版本出现过。你确定用的是3.2.2？

**Comment by lihangleo2** [comment]
你肯定用的是下面这个方式，加子view的是没有任何问题的。不过我也发现是什么问题了。待会会出个包感谢你的支持
           <com.lihang.ShadowLayout
            android:id="@+id/ShadowLayout_image"
            android:layout_width="120dp"
            android:layout_height="36dp"
            android:layout_gravity="center_horizontal"
            android:layout_marginTop="10dp"
            app:hl_cornerRadius="18dp"
            app:hl_cornerRadius_leftTop="0dp"
            app:hl_layoutBackground="@mipmap/test_background_false"
            app:hl_layoutBackground_true="@mipmap/test_background_true"
            app:hl_shapeMode="selected" />
