### ISSUE TITLE
3.2.1修复单边阴影的两头显示不好看的问题，但是3边显示阴影时，剩下的不显示阴影的单边两头却不好看了

### ISSUE THREAD

**Issue by cocowobo** [lihangleo2/ShadowLayout#114]
![Snipaste_2021-09-16_21-50-38](https://user-images.githubusercontent.com/90268640/133660852-eef211e1-0499-4329-9d56-c6841a4d32ed.png)
3.2.0曾经非常好看的 3边显示阴影时，剩下的那个不显示的边的两头圆角非常圆润，好看，
大佬，加个判断，优化下呗

**Comment by lihangleo2** [comment]
嗯嗯。我最近又有点忙了。等空闲的时候会修改的。非常感谢你的使用和积极提issue

**Comment by lihangleo2** [comment]
这块代码已优化。将在下个版本发布
