### ISSUE TITLE
希望 pressed selected ripple 能同时使用

### ISSUE THREAD

**Issue by DuShuYuan** [lihangleo2/ShadowLayout#116]
按下是一个背景，选中又是另一个背景，按下时又有水波纹效果

可以增加属性定义
hl_pressedBackground
hl_selectedBackground
hl_rippleColor

**Comment by lihangleo2** [comment]
你这个问题我不是没考虑过，很鸡肋。弄的太花反而对开源控件自身没有帮助的。谢谢你建议。

**Comment by DuShuYuan** [comment]
原生本就可以一起使用的，不知道为啥要加上限制只能使用一种。
例1.  关注 功能，已关注和未关注状态使用不同的背景和字体颜色，这种需求是正常的啊，同时本身是功能按钮，可以点击，应该拥有水波纹效果
例2. 发送 功能，内容不符合要求时，按钮不可点击；符合要求时可以点击并拥有水波纹效果，两者使用不同的背景颜色区分状态

以上是我有用到的情况，我觉得点击按钮拥有水波纹效果是更好的反馈样式，不应该被限制

**Comment by DuShuYuan** [comment]
> 你这个问题我不是没考虑过，很鸡肋。弄的太花反而对开源控件自身没有帮助的。谢谢你建议。

原生本就可以一起使用的，不知道为啥要加上限制只能使用一种。
例1. 关注 功能，已关注和未关注状态使用不同的背景和字体颜色，这种需求是正常的啊，同时本身是功能按钮，可以点击，应该拥有水波纹效果
例2. 发送 功能，内容不符合要求时，按钮不可点击；符合要求时可以点击并拥有水波纹效果，两者使用不同的背景颜色区分状态

以上是我有用到的情况，我觉得点击按钮拥有水波纹效果是更好的反馈样式，不应该被限制
