### ISSUE TITLE
E AndroidRuntime: java.lang.IllegalArgumentException: width and height must be > 0

### ISSUE THREAD

**Issue by Burns872433647** [lihangleo2/ShadowLayout#117]
在使用过程中出现了一下错误：
应该是createShadowBitmap函数里，在设置RectF的right和bottom时出现的问题。

10-03 09:00:56.440 14962 14962 E AndroidRuntime: java.lang.IllegalArgumentException: width and height must be > 0
--
9710-03 09:00:56.440 14962 14962 E AndroidRuntime: at android.graphics.Bitmap.createBitmap(Bitmap.java:1197)
9810-03 09:00:56.440 14962 14962 E AndroidRuntime: at android.graphics.Bitmap.createBitmap(Bitmap.java:1164)
9910-03 09:00:56.440 14962 14962 E AndroidRuntime: at android.graphics.Bitmap.createBitmap(Bitmap.java:1114)
10010-03 09:00:56.440 14962 14962 E AndroidRuntime: at android.graphics.Bitmap.createBitmap(Bitmap.java:1075)
10110-03 09:00:56.440 14962 14962 E AndroidRuntime: at com.lihang.ShadowLayout.createShadowBitmap(ShadowLayout.java:349)
10210-03 09:00:56.440 14962 14962 E AndroidRuntime: at com.lihang.ShadowLayout.setBackgroundCompat(ShadowLayout.java:285)
10310-03 09:00:56.440 14962 14962 E AndroidRuntime: at com.lihang.ShadowLayout.onSizeChanged(ShadowLayout.java:180)
10410-03 09:00:56.440 14962 14962 E AndroidRuntime: at android.view.View.sizeChange(View.java:19914)
10510-03 09:00:56.440 14962 14962 E AndroidRuntime: at android.view.View.setFrame(View.java:19875)
10610-03 09:00:56.440 14962 14962 E AndroidRuntime: at android.view.View.layout(View.java:19778)
10710-03 09:00:56.440 14962 14962 E AndroidRuntime: at android.view.ViewGroup.layout(ViewGroup.java:6144)
10810-03 09:00:56.440 14962 14962 E AndroidRuntime: at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)

**Comment by lihangleo2** [comment]
是的。建议使用最新版本。修复了很多已知问题。不过从2.0升级到3.0的时候，为了命名规范。修改了很多属性名。 具体你在README里看即可。有不懂的可以加群：209010674
