### ISSUE TITLE
hl_layoutBackground 属性使用图片时，会把边距挡住，使用颜色时是正常的

### ISSUE THREAD

**Issue by amosxb** [lihangleo2/ShadowLayout#119]
同上

**Comment by lihangleo2** [comment]
你好兄弟。经过一天的已经issues的修改和优化。shadowLayout是从阴影控件拓展了shape功能而来。你说的这个确实太像了头像控件了。经过我慎重和对代码的构建看，暂时不会更多从图片出发。建议你使用这方面功能，可以用头像控件加阴影控件实现。非常感谢你的支持
