### ISSUE TITLE
代码设置阴影色报错

### ISSUE THREAD

**Issue by LayneCui** [lihangleo2/ShadowLayout#12]
shadow.setmShadowColor(Color.argb(a, r, g, b));

IllegalArgumentException: width and height must be > 0

**Comment by lihangleo2** [comment]
很明显你的空间里没有任何控件，那么阴影没有大小。你往里面随意放置一个有大小的控件再试试

**Comment by LayneCui** [comment]
ok了，给控件设置阴影时，控件中的内容还没设置上，谢谢！

**Comment by LayneCui** [comment]
不对，顺序调整后还是不行，
而且ShadowLayout 中控件是固定大小的，xml 设置背景颜色起作用，代码设置会报错


<com.lihang.ShadowLayout
            android:id="@+id/shadow2"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            app:hl_cornerRadius="4dp"
            app:hl_dx="2dp"
            app:hl_dy="3dp"
            app:hl_leftShow="false"
            app:hl_topShow="false"
            app:hl_shadowBackColor="#fff"
            app:hl_shadowLimit="3dp"
            app:layout_constraintTop_toTopOf="parent"
            app:layout_constraintLeft_toRightOf="@id/shadow1"
            app:layout_constraintRight_toLeftOf="@id/shadow4"
            >
    <RelativeLayout
            android:id="@+id/rl2"
            android:layout_width="90dp"
            android:layout_height="64dp"
            >


        <com.facebook.drawee.view.SimpleDraweeView
                android:id="@+id/img2"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintLeft_toLeftOf="parent"
                app:layout_constraintTop_toTopOf="parent"
                app:roundedCornerRadius="4dp"
                fresco:placeholderImage="@drawable/bg_r4_color_99_black" />

        <ImageView
                android:id="@+id/imv_vip2"
                android:layout_width="29dp"
                android:layout_height="13dp"
                android:src="@mipmap/icon_home_tag_vip_small"
                android:visibility="gone"/>

        <TextView
                android:id="@+id/tv_name2"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="学院"
                android:textColor="@color/white"
                android:textSize="16sp"
                android:textStyle="bold"
                android:layout_marginTop="11dp"
                android:layout_marginLeft="13dp"/>

        <TextView
                android:id="@+id/tv_study_count2"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="222"
                android:textColor="@color/white"
                android:textSize="10sp"
                android:layout_below="@+id/tv_name2"
                android:layout_marginTop="3dp"
                android:layout_marginLeft="17dp"/>













    </RelativeLayout>
    </com.lihang.ShadowLayout>
