### ISSUE TITLE
【提醒】列表RecyclerView中的item布局使用阴影布局时需注意，一定要修改clickable和focusable为false。

### ISSUE THREAD

**Issue by gs666** [lihangleo2/ShadowLayout#124]
否则会导致adapter的点击事件监听失效。
`        app:clickable="false"
        android:focusable="false"`

**Comment by lihangleo2** [comment]
确实会有这问题，不过当你使用shadowLayout作为itemView去做点击事件 这个问题就不存在的。非常感谢

**Comment by shuaiyinoo** [comment]
我也遇到了 牛逼这个提醒

**Comment by liuhuan8986** [comment]
app:clickable="false" android:focusable="false" 这个我这边无效
 android:clickable="false" android:focusable="false" 这样才行
3.2.4版本
