### ISSUE TITLE
recycleview item中包含阴影 图片点击无效果

### ISSUE THREAD

**Issue by lchang70163** [lihangleo2/ShadowLayout#127]
recycleview item中 用控件包含图片，在使用item的点击效果 不起作用

**Comment by zhufeixiang** [comment]
帮顶  我也遇到了 刚准备发issue的

**Comment by zhufeixiang** [comment]
我是直接作为item整个的父布局的，item的点击事件就没了，换成其他控件例如cardview就没问题

**Comment by lihangleo2** [comment]
因为ShadowLayout的默认模式是pressed。确实会出现这个问题。但是如果作为根布局item的父布局，应该是没有问题的。如果出现这个问题。使用属性app:clickable="false"  可以把ShadowLaout的点击事件取消掉。也可以解决这个问题。如还有问题，reOpen 这个issue
