### ISSUE TITLE
ripple和stroke不能共存

### ISSUE THREAD

**Issue by JacksenLaw** [lihangleo2/ShadowLayout#128]
在设置了shapeMode为ripple后，stroke属性不生效，改为pressed或selected可以生效

ripple：
![8f3b75bee85115a86dc2e72e12f64fc](https://user-images.githubusercontent.com/24518290/148150129-ff4fefed-3268-4d27-b6da-b0ca1debbe48.png)

pressed：
![d3b16c5c26c4fbf543f5491d1da9b74](https://user-images.githubusercontent.com/24518290/148150170-94ea6b07-26fa-47fa-a29d-a7baa24e47ea.png)

selected：
![38ed407553959f425d47b8e460f1a57](https://user-images.githubusercontent.com/24518290/148150012-bd1f7a96-239f-45fd-9021-a4c7d50f2053.png)

**Comment by lihangleo2** [comment]
确实不能共存，在看看大家的反馈吧，如果ripple和stroke需要共存的需求大的话，作者后期会优化的谢谢你的。感谢你的建议。此issues保留半年，如果有同样需求的在此issues上+1

**Comment by 309152665** [comment]
+1

**Comment by zhuangzeqin** [comment]
+1

**Comment by MintQiana** [comment]
+1

**Comment by lihangleo2** [comment]
已修复
