### ISSUE TITLE
很好很强大，但...

### ISSUE THREAD

**Issue by jzllovecat** [lihangleo2/ShadowLayout#129]
都知道安卓原生阴影效果不好，颜色和偏移不能定制且存在版本兼容问题，这个库很好的解决了这些问题，同时增加了shape等扩展属性，但是都会多嵌套一层，本身阴影的绘制就影响性能，然后布局又复杂化了，是不是舍本逐末了？如果要牺牲性能去满足阴影的UI设计，还不如直接说服UI妹子不要阴影了，改个背景色嘛，有对比度不就行了？
        项目目前在使用QMUI，实现的方式是继承原生各View、ViewGroup然后扩展，QMUI的阴影实现同样无法满足UI设计，除了shapemode这样的属性外其他都支持布局里设置，可以用很低的时间成本去替换掉旧代码里的布局。
        希望作者可以参考改进一下，那就牛逼了！

**Comment by lihangleo2** [comment]
之间已经解释过了，ShadowLayout在recycleView里的使用，其实就和系统控件使用是一样的。并没有消耗多大的性能。注意下这段代码public class ShadowLayout extends FrameLayout。就是在FrameLayout上去扩展的。目前作者确实遇到了瓶颈，issues也很少有人提了。如果你有什么方向或者优化的建议，当然要本着这个库的初始目的去，可以留言。非常感谢你的留言
