### ISSUE TITLE
隐藏3边问题

### ISSUE THREAD

**Issue by JetQiao** [lihangleo2/ShadowLayout#132]
请问下博主，控件设置全宽时，当我设置了左右下3边隐藏的时候，上面阴影居中，左右各出现了一段空白，请教下这个怎么解决？3.2.4版本

**Comment by lihangleo2** [comment]
兄弟，能否截图给我看下。或者私聊我。qq：445442684

**Comment by qianjujun** [comment]
> 请问下博主，控件设置全宽时，当我设置了左右下3边隐藏的时候，上面阴影居中，左右各出现了一段空白，请教下这个怎么解决？3.2.4版本

我也发现这个问题，目前我是通过不隐藏左右，然后设置控件宽=原始宽+偏移*2去解决的，这样左右的阴影正好在父控件之外
