### ISSUE TITLE
边框宽度无法设置超过7dp

### ISSUE THREAD

**Issue by venson1992** [lihangleo2/ShadowLayout#133]
![image](https://user-images.githubusercontent.com/14154705/155064651-4a6abd7d-933b-468a-9401-9af64c2ab6f5.png)
建议不要限制UI上的限制，交由开发者自定义
或者增加属性，来控制是否开放限制

**Comment by lihangleo2** [comment]
好的。当时就是为了考虑。如果边框宽度过大时，ui并不美观，也确实没考虑到现实中真的存在需要大边框的需求。感谢，有时间作者会修复这些问题的。

**Comment by lihangleo2** [comment]
已经修复，将在最新一版发布
