### ISSUE TITLE
背景设置了透明度时，会和阴影颜色叠加的情况

### ISSUE THREAD

**Issue by ONiKiDSK** [lihangleo2/ShadowLayout#135]
背景颜色(hl_layoutBackground)设置了透明度后,若再设置阴影颜色(hl_shadowColor),从而影响背景颜色(需要白色透明&蓝色阴影，实际效果变成了蓝白色透明背景)

**Comment by lihangleo2** [comment]
确实是会的。默认情况下hl_shadowColor设置成的白色。换句话说，阴影是在控件的底部。这里可以用PorterDuffXfermode来把阴影部分镂空，但是因为阴影又带了上下左右的偏移，其实并不好操作。加上此需求并不是很强烈，且可以用不透明的颜色值代替。就目前还未有更好的方法解决此问题。如果你有很好的想法，可以联系我。非常感谢~此issues暂时先关了，如果有什么问题，可以再打开。
