### ISSUE TITLE
ShadowLayout在RecyclerView中作为Item，设置ItemClickListener失效

### ISSUE THREAD

**Issue by douxiaofu** [lihangleo2/ShadowLayout#138]
ShadowLayout在RecyclerView中作为Item，设置ItemClickListener失效

**Comment by lihangleo2** [comment]
使用了ShadowLayout想用系统的ItemClickListener，那么必须让ShadowLayout处于根布局，否则就得传入一个onclickListener，然后在逻辑代码里使用setOnClicklistener()使用。非常感谢你的使用。因为ShadowLayout对点击事件处理了。
