### ISSUE TITLE
AndroidStudioFox版本编译error

### ISSUE THREAD

**Issue by shihongjia618** [lihangleo2/ShadowLayout#139]
您好，这是我这边编译报错的日志：
Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
Could not determine artifacts for com.github.lihangleo2:ShadowLayout:3.2.4: Skipped due to earlier error

**Comment by lihangleo2** [comment]
您好，请按照稳定所需，加上必要介入条件。同时也可能和你的网络有关才会导致Could not resolve 问题、非常感谢你的支持
