### ISSUE TITLE
是否可以设置模糊？

### ISSUE THREAD

**Issue by MichaelHappiness** [lihangleo2/ShadowLayout#143]
如题，我们设计师设计的图带有模糊的、、、

**Comment by lihangleo2** [comment]
仔细阅读api，然后根据我下面2个点来调试。如何让阴影更模糊：
1、可以通过设置阴影颜色的透明度，越透明也越模糊
2、可以通过设置阴影的扩散区域，扩散区域越大，越有迷雾效果
