### ISSUE TITLE
如何给x轴和y周分辨设置不同的阴影量？

### ISSUE THREAD

**Issue by ilovexy2tom** [lihangleo2/ShadowLayout#144]
如题

**Comment by lihangleo2** [comment]
兄弟看清下文档呀，看完文档你绝对会，调整下你的学习方式，对以后你的你有帮助。方案：
通过阴影扩散属性+x轴y轴的偏移量属性

**Comment by ilovexy2tom** [comment]
> 兄弟看清下文档呀，看完文档你绝对会，调整下你的学习方式，对以后你的你有帮助。方案： 通过阴影扩散属性+x轴y轴的偏移量属性

可能我没说清楚，如果我x轴偏移，那么看起来就是view的左右阴影量不同，我的理解是当
x偏移 = 1时，left=5，right = 7,top=6，bottom=6，那我的需求是y的阴影是12dp，x是8dp，我看文档只有一个limit属性调整四周的

不知道我说的这个算不算，x和y不同的阴影量？

**Comment by lihangleo2** [comment]
额、你这个需求。确实还未实现，也就是x轴的阴影区域总长度和y轴阴影总长度不一样。我会记住的。有时间我再修改。非常感谢！

**Comment by ilovexy2tom** [comment]
> 额、你这个需求。确实还未实现，也就是x轴的阴影区域总长度和y轴阴影总长度不一样。我会记住的。有时间我再修改。非常感谢！

不客气，好的。

**Comment by lihangleo2** [comment]
经过一番探索后，因为要实现一个比较圆滑，过度自然的阴影，暂时无法实现x轴和y轴不同的阴影量。非常感谢你支持

**Comment by ilovexy2tom** [comment]
> 经过一番探索后，因为要实现一个比较圆滑，过度自然的阴影，暂时无法实现x轴和y轴不同的阴影量。非常感谢你支持

好的，那个需求也不存在了。非常感谢回复，你的库很好用，一直在使用，谢谢
