### ISSUE TITLE
在首页底部导航套ShadowLayout的问题

### ISSUE THREAD

**Issue by startong** [lihangleo2/ShadowLayout#145]
<img width="209" alt="企业微信截图_20220506164257" src="https://user-images.githubusercontent.com/27007471/167098990-aad5740c-584b-4497-9f0c-225bb015e532.png">
这是我把导航放在顶部的效果，这种阴影效果是我想要的，但是不可能把导航放在顶部吧

<img width="212" alt="企业微信截图_20220506164702" src="https://user-images.githubusercontent.com/27007471/167099117-5cb77504-c799-4a69-bc44-db2434591e8f.png">
<img width="408" alt="企业微信截图_20220506164408" src="https://user-images.githubusercontent.com/27007471/167099143-33bebf96-d802-45a1-8d4f-af9ff87b50b0.png">
这是我把导航放到底部了，我这个只需要显示导航上方的阴影，所以我设置了左右下的阴影不显示，但是阴影效果却和顶部的那个效果明显不一致，这个是为什么啊。。。

**Comment by startong** [comment]
补一张图，可以明显看到差别的

<img width="178" alt="企业微信截图_20220506165308" src="https://user-images.githubusercontent.com/27007471/167099906-728e9109-102d-4b9a-9248-b18409334669.png">

**Comment by lihangleo2** [comment]
![28](https://user-images.githubusercontent.com/38236349/167240217-8bf38b23-bd08-402a-8ff8-096f1f53796a.png)
1、首先我在demo里试了，并不会出现你这样的问题！
2、shadowLimit的值要与你适配方案的值保持一致，否则取出计算的话会有差异
3、其次阴影是占据位置的。所以你FrameLayout.blow的时候最好用一个marginTop = - shadowLimit。只让阴影盖在上面布局上
4、不管是哪个第三方，你都要在demo上测试是否可行，除去环境问题后，才能知道问题真正出现在什么地方、
如果还有疑问，open这个issue

**Comment by startong** [comment]
嗯嗯，感谢大佬给的思路，感谢，已经解决了，是我控件above的问题
