### ISSUE TITLE
还没有完全转换到andoridx

### ISSUE THREAD

**Issue by tzt1994** [lihangleo2/ShadowLayout#146]
<img width="1440" alt="QQ20220508-141054@2x" src="https://user-images.githubusercontent.com/15625580/167284268-cbbd46b8-3ab5-4113-b583-9cf154e0f441.png">

**Comment by zdxiang** [comment]
The same with me

**Comment by lihangleo2** [comment]
兄弟，我上面写的是demo转androidX。如果用的第三方库想要在AndroidX里运行，在你的gradle的配置文件里gradle.properties加上以下2句话：
# https://developer.android.com/topic/libraries/support-library/androidx-rn
android.useAndroidX=true
# Automatically convert third-party libraries to use AndroidX
android.enableJetifier=true
你可以看到这句官网给的解释也非常清楚，允许第三方库转成AndroidX：convert third-party libraries to use AndroidX
非常感谢你的支持！

**Comment by tzt1994** [comment]
有计划把library转到Andoridx吗

**Comment by lihangleo2** [comment]
暂时没有哦。既然官网给了解决方案,,意思你不用担心使用，gradle自动帮你转成androidX。而且这边要考虑到没有使用androidX的同学，如果改了的话。有的项目不是androidX的，那这个控件就使用不了了。要考虑到兼容啊
