### ISSUE TITLE
大佬，为啥边框的宽度传递的是int型，不是浮点型呢

### ISSUE THREAD

**Issue by amosxb** [lihangleo2/ShadowLayout#148]
我想设置0.5f这样的值都不行。

**Comment by lihangleo2** [comment]
兄弟你提的很好。项目里本来就是float值，当时也是issues提需要动态设置值才加上的。后期我会统一规范，非常感谢你的提议。我最近在找工作，暂且还没有时间！！

**Comment by lihangleo2** [comment]
已经修复，将发布到最新一版本中去

**Comment by lihangleo2** [comment]
经过一番探索哦。其实系统的Shape也是用到GradientDrawable这个类，这个类接受的也是int型。而且你用系统的shape测试会发现，他其实是经过四舍五入的，所以探索下来，还是以int型为主。非常感谢你的支持
