### ISSUE TITLE
建议增加虚线边框

### ISSUE THREAD

**Issue by qq2540040142** [lihangleo2/ShadowLayout#155]
![image](https://user-images.githubusercontent.com/56993378/190288220-ca1b3f0a-334f-42dd-8b77-dc34b60356d5.png)

**Comment by lihangleo2** [comment]
好的。等不忙了，我会加上的

**Comment by lihangleo2** [comment]
这里已经加上了虚线边框。但是如果是一条线的，系统shape也还是会有间隙，并不好掌握一条竖直线，和一条横线在ui上的布局。大概明天会更新上。
