### ISSUE TITLE
最新版3.2.6，无法下载依赖

### ISSUE THREAD

**Issue by boiyun** [lihangleo2/ShadowLayout#159]
最新版3.2.6，下载不了呀，是我网不行吗

**Comment by jiqianwen** [comment]
我也依赖不了

**Comment by lihangleo2** [comment]
不可能吧，都编译通过了啊

**Comment by jiqianwen** [comment]
> 不可能吧，都编译通过了啊

3.2.5和3.2.6都试过了依赖不下来，3.2.4正常

**Comment by WeiLianYang** [comment]
3.2.7 也下不了

**Comment by jiqianwen** [comment]
3.2.8依旧还是不行= =
![QQ截图20221031153833](https://user-images.githubusercontent.com/26268908/198956162-141fd9e0-3020-4a73-9a74-a33c6e99c85d.png)

**Comment by lihangleo2** [comment]
稍等，兄弟们。暂时用3.2.4的。我在尝试，最新的gradle遇到了问题。

**Comment by jiqianwen** [comment]
> 稍等，兄弟们。暂时用3.2.4的。我在尝试，最新的gradle遇到了问题。

好的，作者辛苦了

**Comment by lihangleo2** [comment]
最新以来3.3.1，稍后会更新md
