### ISSUE TITLE
RecyclerView中添加ShadowLayout，出现内存无法释放的情况

### ISSUE THREAD

**Issue by panlinnadede** [lihangleo2/ShadowLayout#16]
在一个Activity中写了一个RecyclerView，RecyclerView中的每个Item中包含一个ShadowLayout，进入页面之前的内存为60M。进入页面开始滚动，再退出页面，强制gc之后，内存为72.5M。近乎每次内存都会有10多M无法释放，查看内存的工具使用的是android studio的profiler

如果RecyclerView中的每个Item包含的是一个TextView，就不会存在问题，测试代码请查看附件
[TestShadow.zip](https://github.com/lihangleo2/ShadowLayout/files/3807100/TestShadow.zip)

**Comment by lihangleo2** [comment]
兄弟非常感谢你的细心测试，你可以一直来回事。最后是会被回收的，只是垃圾回收机制并不那么高效和及时。关于这方面我有做过相关的分析，可以看看这个https://juejin.im/post/5d4c1392f265da03bc126584#heading-12

**Comment by lihangleo2** [comment]
如果还有什么麻烦。再反馈下。非常感谢！

**Comment by lihangleo2** [comment]
兄弟我最新更新了一版，2.1.4。专门针对阴影bitmap的优化。你试试看
