### ISSUE TITLE
一点小建议

### ISSUE THREAD

**Issue by qianjujun** [lihangleo2/ShadowLayout#161]
阴影的实现，为什么要借助设置背景而去创建bitmap呢 ，何不直接draw出来。阴影大小的变化和偏移也可以直接通过重写onMeasure和onLayout去实现 ，setPadding和setBackGround都有可能导致再次重新布局
还有背景图片的功能和单独虚线功能完全可以去掉 ，这些跟控件主旋律不符，做个好看而且干净的控件。加油

**Comment by lihangleo2** [comment]
每个人都有每个人的想法。最开发布的版本就是你说的简洁效果。但随着不同人的issue，一直在优化。保证原有功能的时候再拓展，就比如这次的虚线，如果不用可以完全忽略这个属性。当然你第一条的建议待考虑。10月的更新，是涨了很久的issue更新的，起核心也变成了gridentDrawable类去实现。接下来看看反馈怎么样吧。感谢
