### ISSUE TITLE
阴影不占位

### ISSUE THREAD

**Issue by maclaylq** [lihangleo2/ShadowLayout#162]
如何让阴影不占位。现在我看layout是自动添加了padding。也就是在view的外部显示。不影响view的大小。listview中使用。

**Comment by lihangleo2** [comment]
目前是占位的，你可以自己放大一定阴影大小。这个空间主要是根据你的ui自己尝试着去调。想要不占据位置，就要去研究下DecorView了。比如你item上做的动画超出了item的范围，就要复制一个view添加到对应位置的DecorView上去做动画覆盖他，这样动画的范围就可以超出item区域，这只是一种思路

**Comment by maclaylq** [comment]
恩，有找到一些资料，这里先替换为了cardview。后续有时间再看看。
