### ISSUE TITLE
3.2.3版本不存在了吗？

### ISSUE THREAD

**Issue by occeanyang** [lihangleo2/ShadowLayout#164]

**Comment by asker517** [comment]
好像发了这个新版本之后，老是存在这个问题。。我是3.2.4一直没法儿下载下载。。

**Comment by lihangleo2** [comment]
建议直接用新版本。所有的版本在wiki上都有介绍的。

**Comment by lihangleo2** [comment]
之前的版本都是存在的。有可能因为jitpack大姨妈的问题，可能需要翻墙vpn一下。正常情况都是能download下来的

**Comment by occeanyang** [comment]
好的 感谢各位解惑 这里不一一回复了
