### ISSUE TITLE
在Androidstudio中预览xml文件失败

### ISSUE THREAD

**Issue by nodzhang** [lihangleo2/ShadowLayout#166]
在Androidstudio中预览xml文件失败，AS版本：Android Studio Dolphin | 2021.3.1 Patch 1
报错如下：
![AD213850-7BE5-4AEB-906D-2654BA757608](https://user-images.githubusercontent.com/20973153/201884284-9c172617-77d8-4f62-9ea0-f9f841e517c3.png)

java.lang.NullPointerException   at com.bumptech.glide.module.ManifestParser.parse(ManifestParser.java:36)   at com.bumptech.glide.Glide.initializeGlide(Glide.java:232)   at com.bumptech.glide.Glide.initializeGlide(Glide.java:223)   at com.bumptech.glide.Glide.checkAndInitializeGlide(Glide.java:184)   at com.bumptech.glide.Glide.get(Glide.java:168)   at com.bumptech.glide.Glide.getRetriever(Glide.java:689)   at com.bumptech.glide.Glide.with(Glide.java:801)   at com.lihang.GlideRoundUtils$3.onLayoutChange(GlideRoundUtils.java:85)   at android.view.View.layout_Original(View.java:23161)   at android.view.View_Delegate.layout(View_Delegate.java:91)

**Comment by lihangleo2** [comment]
1. 具了解，这可能和你的版本和studio有关
2. 其次，再设置图片的时候，ShadowLayout的做法是利用了glide，因为想使用它非常智慧的缓存方式。所以当使用图片背景的时候，xml也是实时预览不了的。
