### ISSUE TITLE
jitpack源 3.2.4以及 3.2.3版本失效

### ISSUE THREAD

**Issue by 1364222510** [lihangleo2/ShadowLayout#167]

**Comment by xuaba** [comment]
对啊，

**Comment by Sola1** [comment]
3.3.x之后核心机制改变了，对比原有效果是否有影响

**Comment by Fomovet** [comment]
+1

**Comment by Lemniscate317** [comment]
+1

**Comment by hexin9456** [comment]
+1

**Comment by hexin9456** [comment]
最低支持到了21了。这个是不是有点高啊！！！

**Comment by kouhengsheng** [comment]
3.2.4和3.2.3失效了感觉挺麻烦了，3.3.x以后只支持21以上的版本，我们APP要兼容api19，没办法用3.3.x

**Comment by lihangleo2** [comment]
好的 兄弟们。这个是jitpack的bug，我确定我没有删除过版本

**Comment by lihangleo2** [comment]
我抽时间尽快修复

**Comment by lihangleo2** [comment]
有依赖问题的可以看这里
- [3.2.4依赖问题解决](https://github.com/lihangleo2/ShadowLayout/blob/master/showImages/problem.md)
