### ISSUE TITLE
设置不可点击时，背景色无法代码设置的问题

### ISSUE THREAD

**Issue by boiyun** [lihangleo2/ShadowLayout#168]
最新版3.3.2，如果布局中设置app:clickable="false"，只能设置hl_layoutBackground_clickFalse，无法通过代码动态设置，是否可以加上这个呢？

**Comment by goodluckier** [comment]
是的，看源码是false不设置背景色

**Comment by boiyun** [comment]
我目前是设置颜色之前改成可点击，设置完颜色后，再设置为不可点击。

**Comment by goodluckier** [comment]
> 我目前是设置颜色之前改成可点击，设置完颜色后，再设置为不可点击。

等作者看看吧，我现在用的view.setEnabled

**Comment by lihangleo2** [comment]
一般情况下设置不可点击了，按钮是不可点击的状态。如果设置了hl_layoutBackground_clickFalse属性，那么就会按这个属性显示，如果没有设置这个属性，原先是什么样子的就是什么样子的。如果还是不符合你们的应用场景，麻烦可以详细叙述一遍并重新打开这个issue，非常感谢~
