### ISSUE TITLE
希望兼容下动态设置背景以及点击导致的问题

### ISSUE THREAD

**Issue by Uenchi** [lihangleo2/ShadowLayout#169]
场景：
需要动态设置背景 的 Item
因为开启点击= true，导致无法监听 Item 的点击事件

**Comment by Uenchi** [comment]
当前解决方式：
app:hl_shapeMode="selected"
setLayoutBackgroundTrue

**Comment by lihangleo2** [comment]
1、如果item整个都用的ShadowLayout，item的点击事件确实会被遮挡，这个时候建议传入onClickListener这种方式解决。如果item不是整个使用，那么其就相当是个Button。
2、ShadowLayout一直是支持动态设置背景的，因为你上下滑动的时候涉及到了复用。建议你数据源里，可以放上资源id，然后在adapter的onBinderView的时候去设置一次。

如果还遇到问题，再详细叙述下，并重新打开这个issue，非常感谢~
