### ISSUE TITLE
建议以前的版本不去除

### ISSUE THREAD

**Issue by Lincaiqin0605** [lihangleo2/ShadowLayout#174]
implementation 'com.github.lihangleo2:ShadowLayout:3.2.4'

遇到的情况是找不到该引用了 顺回来看看为啥呜呜呜 建议楼主重视这个问题哈

**Comment by songchengdi** [comment]
遇到同样的问题，只能拉取新版本，旧版本拉不到

**Comment by Lincaiqin0605** [comment]
> 遇到同样的问题，只能拉取新版本，旧版本拉不到

只能引入最新版本了 突然用不了估计是旧版本被删除了  作者可能没看

**Comment by zhuncoder** [comment]
同样问题，作者重视一下

**Comment by lihangleo2** [comment]
收到  我找哥事件重点看下，我不可能去删除的，可能是jitpack的bug

**Comment by lihangleo2** [comment]
通宵达旦，想骂人了。有依赖问题的可以看这里
- [3.2.4依赖问题解决](https://github.com/lihangleo2/ShadowLayout/blob/master/showImages/problem.md)
