### ISSUE TITLE
建议阴影缩小比例可以通过自定义属性后者set方法设置。

### ISSUE THREAD

**Issue by liming870906** [lihangleo2/ShadowLayout#175]
`//优化阴影bitmap大小,将尺寸缩小至原来的1/4。
        dx = dx / 4;
        dy = dy / 4;
        shadowWidth = shadowWidth / 4 == 0 ? 1 : shadowWidth / 4;
        shadowHeight = shadowHeight / 4 == 0 ? 1 : shadowHeight / 4;
        cornerRadius = cornerRadius / 4;
        shadowRadius = shadowRadius / 4;`

**Comment by lihangleo2** [comment]
这个属性权重不大，即使不缩小，也不会有问题。只不过刚好模糊阴影刚好符合分辨率低的阴影bitmap
