### ISSUE TITLE
大佬你好  有个问题请教下

### ISSUE THREAD

**Issue by 756230883** [lihangleo2/ShadowLayout#181]
![1686041177109](https://github.com/lihangleo2/ShadowLayout/assets/9440937/9e0264d2-27a6-4790-a0b6-ab53d540fc5f)
如图所示 当页面里不是白色 会明显感觉到有一条白边 我想把背景设置成全透明  只留下阴影 发现并不行 请问大佬有什么好的解决方案吗

**Comment by lihangleo2** [comment]
阴影默认为白色背景把他设置成透明色，底部的布局设置marginTop = "-shadowLimit的高度"，即可达到你的效果。非常感谢你的支持

**Comment by lihangleo2** [comment]
可以查看下源码 ShadowLayout默认是白色背景。有机会我会更新新的版本，把他改成透明的。有问题的话，在打开这个Issue
