### ISSUE TITLE
需求：可以增加一个 hl_textColor_clickFalse  属性吗

### ISSUE THREAD

**Issue by animus198656** [lihangleo2/ShadowLayout#182]
不可点击时可以通过 hl_layoutBackground_clickFalse 设置背景色，但是一般按钮不可点击时文字颜色也会相应变化。可以增加 hl_textColor_clickFalse 属性来改变文字颜色吗？

**Comment by lihangleo2** [comment]
这个可以通过动态设置字体颜色可以解决 而且也不难。暂时不会添加，目前来看 只有你提出这一个issue。感谢你得使用
