### ISSUE TITLE
提个小小的建议

### ISSUE THREAD

**Issue by clunyes** [lihangleo2/ShadowLayout#185]
代码可以稍微稍微优化一下

**Comment by lihangleo2** [comment]
嗯  因为功能多，所以源码回显得乱一些 但是根据方法名和属性名 应该不难看懂，因为对外提供的方法和属性已经确定，乱修改的话，回影响忠实的使用者。感谢你的建议 以后的开源或者项目里 我会更佳往代码读懂上去考虑。
