### ISSUE TITLE
建议嵌套点击穿透

### ISSUE THREAD

**Issue by xiaxinqing** [lihangleo2/ShadowLayout#186]
首先，感谢作者提供的ShadowLayout库，在项目中着实提高了很多效率。

在使用过程中发现 ShadowLayout 嵌套ShadowLayout，点击里面的ShadowLayout时，无法触发外部的点击时间和水波纹。是拦截了事件分发吗

**Comment by lihangleo2** [comment]
感谢你的提议  我有空修复下

**Comment by lihangleo2** [comment]
兄弟，我具体问下，你是点击里面的按钮，里面的按钮只有点击事件，不带水波纹和其他样式，想让父ShadowLayout触发样式是吗？

**Comment by lihangleo2** [comment]
如果你里面有点击事件，事件会被消费掉。不可能穿透到底部。就比如，你再recycleView里的item里有个按钮的点击事件，点击按钮，并不可能做到，按钮具有点击事件，item的点击事件还能触发。建议你这边，合理使用控件。
