### ISSUE TITLE
颜色透明变大后，西周有明显的边框痕迹

### ISSUE THREAD

**Issue by tt905** [lihangleo2/ShadowLayout#19]
颜色透明变大后，西周有明显的边框痕迹

**Comment by lihangleo2** [comment]
边框痕迹是我特意加上的，之前测试时，在颜色透明度过于透明时候，控件区域和布局背景有点不明显。所以加上了。加上后也不矛盾，阴影只是控件的阴影，控件还是有自身区域的

**Comment by tt905** [comment]
能给个去掉的方法吗

**Comment by smartsimba** [comment]
痕迹太明显了。太影响体验了。。怎么去掉呢

**Comment by lihangleo2** [comment]
试试最新的库2.1.6.如果还是有问题，请联系我QQ445442684。感谢你的支持

111 <notifications@github.com> 于2019年11月28日周四 下午2:48写道：

**Comment by Joslyn-Chen** [comment]
还是有痕迹，没那种渐变效果，圆角处比较明显

**Comment by lihangleo2** [comment]
哦 是的。我这是为了区分阴影和阴影控件区域设置的

Jun Chen <notifications@github.com> 于2020年1月14日周二 下午4:53写道：

**Comment by gtf35** [comment]
可是很影响体验呀🤔，我以为是bug，结果发现是特性🤣🤣🤣
