### ISSUE TITLE
希望适配 androidX

### ISSUE THREAD

**Issue by dyguests** [lihangleo2/ShadowLayout#190]
是的，我知道可以用 `android.enableJetifier=true`。

不幸的是，我是做SDK的，提供给别的应用（Unity跨平台）使用。

目标用户并不会配置`android.enableJetifier=true`。

### **希望大佬能出个适配androidX的版本**

sad...

**Comment by lihangleo2** [comment]
3.4.0已经适配AndroidX，感谢你的使用反馈
