### ISSUE TITLE
全体布局黑色背景下看不到阴影

### ISSUE THREAD

**Issue by AXwjg** [lihangleo2/ShadowLayout#194]
<com.lihang.ShadowLayout
                android:id="@+id/mShadowLayout2"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="center_horizontal"
                app:hl_cornerRadius="10dp"
                app:hl_shadowColor="@color/cooking_red"
                android:layout_marginTop="@dimen/zr_20_dp"
                app:layout_constraintTop_toBottomOf="@+id/tv_tos"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintEnd_toEndOf="parent"
                app:hl_shadowLimit="15dp">

                <TextView
                    android:id="@+id/txt_test"
                    android:layout_width="wrap_content"
                    android:layout_height="36dp"
                    android:gravity="center"
                    android:paddingLeft="10dp"
                    android:paddingRight="10dp"
                    android:text="圆角"
                    android:textColor="#000" />
            </com.lihang.ShadowLayout>

它的父布局是黑色

**Comment by lihangleo2** [comment]
阴影颜色不设置颜色透明度时，默认透明度为16%，如果想让阴影明显一点，可以通过调整颜色透明度去让阴影展示的是否够明显，如果上你看用将cooking_red加上一个50% 或者80%的透明度，去看看阴影的变化

**Comment by xpx1003** [comment]
好像跟透明度没关系，用红色都看不出来
