### ISSUE TITLE
小米9给阴影控件子view设置背景颜色后，圆角显示异常，部分圆角不显示

### ISSUE THREAD

**Issue by q805699513** [lihangleo2/ShadowLayout#21]

**Comment by lihangleo2** [comment]
shadowLayout相当于一个ViewGroup。可以修改的。但是有个问题是他的背景颜色值是在底层，如果你再recycleView的item里，也就是shadowLayout的子view了设置了background的话，会覆盖掉shadowLayout的背景。还是设计有bug，有时间我再改改
