### ISSUE TITLE
crash了

### ISSUE THREAD

**Issue by lyx0224** [lihangleo2/ShadowLayout#23]
width and height must be > 0

- [ ] ....ShadowLayout.drawableToBitmap(ShadowLayout.java:289)

**Comment by zilianliuxue** [comment]
java.lang.IllegalArgumentException

width and height must be > 0

**Comment by lihangleo2** [comment]
这个问题在2.1.5的版本修复了（还增加了自带shape功能，感谢支持）。请尽快使用implementation 'com.github.lihangleo2:ShadowLayout:2.1.5'

**Comment by lihangleo2** [comment]
2.1.5应该是没这个问题的，请问是2.1.5版本出现的吗？如果不旧版本我就关闭这个issues了

**Comment by lihangleo2** [comment]
兄弟我测试过了。我这边是没问题的。如果有问题。请加我QQ445442684。把bug复现一遍。非常感谢你的支持
