### ISSUE TITLE
圆角属性不生效???还望大佬指教

### ISSUE THREAD

**Issue by lydlovezjr** [lihangleo2/ShadowLayout#27]
环境:
依赖库最新版:2.1.6
手机:小米8 
miui系统:MIUI11
Android版本:10
![360截图20200224203747836](https://user-images.githubusercontent.com/19246347/75153422-57c3d300-5746-11ea-945e-457115b1773d.jpg)
<img width="624" alt="微信截图_20200224203906" src="https://user-images.githubusercontent.com/19246347/75153426-5abec380-5746-11ea-844f-96dfcffe2105.png">

**Comment by lihangleo2** [comment]
你看下我demo生效吗。如果生效，把app：hl_cornerRadius="5dp"写死。具体为什么失效，我抽时间检验一遍，感谢你的支持

**Comment by lihangleo2** [comment]
我刚刚试试了下，是能正常读取dimens里的数值的。你再试试，在你的小米手机上是否能正常跑起来我的demo
