### ISSUE TITLE
关于阴影limit和偏移量导致的padding，有一点小疑问

### ISSUE THREAD

**Issue by zeropercenthappy** [lihangleo2/ShadowLayout#29]
比如说设置了15dp的阴影limit，再设置5dp的hl_dy偏移量，会导致上边和下边各自都分别有20dp的padding，下边的padding我理解，但是上边为何也要有同样的padding量？

实际上在这种情况里上边并不需要20dp这么多的偏移量去绘制阴影才对，现在强行设置了这么多偏移量会导致很难去调整与其它View的间距，完全把上边的阴影关掉又显得很突兀。

暂时还没时间去研究源码，可以大概说一下这么设计的目的吗？或者以后有没有可能优化一下这种情况？

**Comment by lihangleo2** [comment]
兄弟。你这个建议很中用。之前根本没有考虑到这块。我会尽快更新到2.1.7谢谢你的关注。

**Comment by lihangleo2** [comment]
兄弟，控件已经更新到了2.1.7!可以满足你的要求。可以查看新属性11、 控件区域是否对称，默认是对称。不对称的话，那么控件区域随着阴影区域走:app:hl_isSym="false"

**Comment by zeropercenthappy** [comment]
好的，控件很易用，准备有空看一看源码;p
