### ISSUE TITLE
阴影控件不支持代码添加

### ISSUE THREAD

**Issue by zhjun2016** [lihangleo2/ShadowLayout#30]
阴影控件不支持代码添加吗，只能在 xml里面用?

**Comment by lihangleo2** [comment]
自定义控件就支持啊。在你的Activity：
`
ShadowLayout shadowLayout = new ShadowLayout(this);  

RelativeLayout.LayoutParams layoutParams = new RelativeLayout.LayoutParams(300,150);
shadowLayout.setLayoutParams(layoutParams);
addContentView(shadowLayout, layoutParams);`
