### ISSUE TITLE
能否实现从图片底边取样生成阴影呢

### ISSUE THREAD

**Issue by hiliving** [lihangleo2/ShadowLayout#33]
参考华为主题app的banner，卡片底边的阴影是图片底边的高斯模糊，有种溢出的感觉

**Comment by lihangleo2** [comment]
你说的这个能实现，但是不太友好。我的控件是针对布局的。假如布局里的源图片不是ShadowLayout的满屏。那么背景会有些拉伸，效果也不是很好。只能说单独针对图片做一个自定义view。感谢你的建议
