### ISSUE TITLE
不能动态改变mBackGroundColor的值

### ISSUE THREAD

**Issue by fmy86305969** [lihangleo2/ShadowLayout#37]
@lihangleo2

**Comment by fmy86305969** [comment]
用mBackGroundColorClicked也只是2种颜色值切换 ，如果有第三种状态就不支持了

**Comment by lihangleo2** [comment]
一般selector是2种shape去切换。第三种的话请问是在什么场景呢？ 如果合适我就加上。

**Comment by lihangleo2** [comment]
是不是我代码设置颜色值mBackGroundColorClicked，没有加上。如果加上代码动态设置颜色值 是否满足你的需求？

**Comment by fmy86305969** [comment]
我已经用其他方式实现了，不过你这边暴露接口的话比较方便些。之前说错了，因该是mBackGroundColor的颜色值不能代码动态改变。这个背景色我这边会有第三种状态。。。

**Comment by jiqiuyu** [comment]
同上，mBackGroundColor 有多个色值 需要
