### ISSUE TITLE
更改了包裹的控件的背景颜色之后，没有阴影效果

### ISSUE THREAD

**Issue by hexiaxia** [lihangleo2/ShadowLayout#39]
我更改了TextView的背景颜色之后，就没有阴影效果了

**Comment by lihangleo2** [comment]
包裹的控件不要设置背景颜色 如果要设置。通过ShadowLayout的app:hl_shadowBackColor="#fff"属性设置。包裹shape和selector都是通过ShadowLayout去设置的
