### ISSUE TITLE
绘制阴影不成功

### ISSUE THREAD

**Issue by DaDaChris** [lihangleo2/ShadowLayout#4]
hl_shadowColor绘出的阴影为空白

**Comment by lihangleo2** [comment]
你下载我的demo也绘制不出来吗？

**Comment by DaDaChris** [comment]
透明度为ff就跟等于00一样了

**Comment by lihangleo2** [comment]
当然，阴影必须给一个透明度，看源码
`* The alpha of the shadow will be the paint's alpha if the shadow color is
     * opaque, or the alpha from the shadow color if not.
     */
    public void setShadowLayer(float radius, float dx, float dy, int shadowColor) {
      mShadowLayerRadius = radius;
      mShadowLayerDx = dx;
      mShadowLayerDy = dy;
      mShadowLayerColor = shadowColor;
      nSetShadowLayer(mNativePaint, radius, dx, dy, shadowColor);
    }`

**Comment by lihangleo2** [comment]
点进去看系统源码setShadowLayer；有一段介绍是  
/* The alpha of the shadow will be the paint's alpha if the shadow color is  
* opaque, or the alpha from the shadow color if not.  
*/

**Comment by lihangleo2** [comment]
阴影必须要透明度。已经更新了README.md

DaDaChris <notifications@github.com> 于2019年8月10日周六 下午2:55写道：
