### ISSUE TITLE
Seletor的Pressed样式bug

### ISSUE THREAD

**Issue by zhpanvip** [lihangleo2/ShadowLayout#41]
demo中selector的pressed样式，手指按下时会变成pressed样式，抬起后变回正常。
但是如果手指按下后移动到Button外边再抬起手指，Button就变成了Pressed样式了。

**Comment by lihangleo2** [comment]
确保使用的模式是否正确，我刚刚试了，好像不会。你用的是什么手机，方便跟我联系吗QQ445442684

**Comment by lihangleo2** [comment]
是否是单独使用pressed的模式时会出现这个bug？或者你可以把demo下下来，在ShadowLayout里的手势操作里debug下，

**Comment by zhpanvip** [comment]
华为p30,跑的是你蒲公英的包。手指按到button上，然后手指不要离开屏幕滑动到button外部抬起手指就可以复现。
