### ISSUE TITLE
shadowback能支持颜色渐变的话就更好了

### ISSUE THREAD

**Issue by lanyu007** [lihangleo2/ShadowLayout#43]

**Comment by lihangleo2** [comment]
你是说阴影颜色渐变吗？

**Comment by zhaoxiuyu** [comment]
@lihangleo2  我下载APK体验了一下， 那个 点我selector的pressed样式，这个按钮，按下之后手指滑开之后在抬起，颜色不会恢复。是不是bug？

**Comment by lihangleo2** [comment]
按下颜色变了，抬起不会恢复问题。下个版本会更新。  目前阴影不支持渐变颜色。
