### ISSUE TITLE
如果layout里面是  一整张 imagview 的话，角还是存在，没有被裁剪掉

### ISSUE THREAD

**Issue by Yuanarcheannovice** [lihangleo2/ShadowLayout#44]

**Comment by lihangleo2** [comment]
好的，有空我会加上的。感谢你的建议

**Comment by lihangleo2** [comment]
这里考虑了很久。如果最低成本实现，用glide就能实现了。所以这里shadowLayout不建议加上这个功能，稍后会有，通过glide的方式去实现这个功能

**Comment by ymwm-lxl** [comment]
通过glide 方式加的话不支持 android:scaleType="centerCrop"
