### ISSUE TITLE
单词拼写错误

### ISSUE THREAD

**Issue by lydlovezjr** [lihangleo2/ShadowLayout#45]
<img width="641" alt="微信截图_20200722111830" src="https://user-images.githubusercontent.com/19246347/88130515-5cb18380-cc0d-11ea-84f8-2fa9885bf0a5.png">

**Comment by lydlovezjr** [comment]
right

**Comment by lydlovezjr** [comment]
Padding单词也拼写错了

**Comment by lihangleo2** [comment]
哈哈哈   好的 下个版本一起改正
