### ISSUE TITLE
支持各种各样的形状?

### ISSUE THREAD

**Issue by oh-Rin** [lihangleo2/ShadowLayout#46]
感谢开源那么酷的layout！有可能会添加其他形状的支持吗，就像https://github.com/florent37/ShapeOfView

**Comment by lihangleo2** [comment]
当然可以支持了，就是通过BitmapShader以及canvas.drawPath去实现的。文中通过glide去处理了存储。如果大家都需要此功能，后续会加上。非常感谢你的支持。如果使用中有任何bug及体验不妥的地方，欢迎issues
