### ISSUE TITLE
isShowShadow可见性问题

### ISSUE THREAD

**Issue by qiushui95** [lihangleo2/ShadowLayout#49]
isShowShadow未暴露，无法代码设置。
因为特殊原因，我不能使用xml写布局，只能代码new

**Comment by lihangleo2** [comment]
嗯 这里暂时未提供 代码设置isShowShadow的属性，后续会加上。那么你可以不通过依赖，将demo里的shadowLibrary手动集成在项目里。然后在ShadowLayout控件内增加主动设置的方法。后续等issues累计到一定数量的时候，会更新一版本。非常感谢你的支持

**Comment by qiushui95** [comment]
我通过反射修改的。后续更新麻烦@我一下，谢谢

**Comment by lihangleo2** [comment]
mShadowLayout.setShowShadow(); 最新版已经加上了设置阴影是否可见。感谢你的支持
