### ISSUE TITLE
可以支持圆角位置自定义嘛  不是全部都设置圆角，有可能会出现只有左上右上需要圆角，左下右下不需要圆角的情况呢

### ISSUE THREAD

**Issue by hyr0318** [lihangleo2/ShadowLayout#5]

**Comment by lihangleo2** [comment]
嗯，你这个想法可以。目前暂不支持，但你目前可以这样，不适用布局的背景填充色属性，自己在被嵌套的子控件background里放上你所说的shape。虽然阴影的圆角暂时没办法改，但能达到你要的效果
