### ISSUE TITLE
[Q] demo中将根布局添加背景色#000无法正常凸显阴影

### ISSUE THREAD

**Issue by rabbitknight** [lihangleo2/ShadowLayout#52]
如题。
在demo中 将页面添加```    android:background="#000" ``` 即纯黑后。阴影效果丢失。

感谢开源~

**Comment by lihangleo2** [comment]
![black_ui](https://user-images.githubusercontent.com/38236349/92192216-169c4080-ee98-11ea-8030-94dfdce66c88.jpg)
阴影不会消失，只是不是那么明显！。如果改成白色的，可以看到是有阴影在的。

**Comment by lgGuo** [comment]
黑色背景除了阴影设置成白色有一点点效果外，其他颜色阴影一点也没有
