### ISSUE TITLE
颜色太淡，希望能够有重绘制的选项

### ISSUE THREAD

**Issue by ymwm-lxl** [lihangleo2/ShadowLayout#54]
绘制出来的颜色太淡了，有时候周围控件没办法留出足够的距离以供绘制阴影，所以在较小的距离中也需要有明显的阴影效果，现在这个库使用的话效果很不明显的。
这个库使用与思路很棒，感谢作者。

**Comment by lihangleo2** [comment]
阴影的颜色可以根据 阴影颜色值的透明度来实现的。不设置颜色透明度，默认透明度为16%，  在设置颜色的时候，试试阴影的扩散区域和阴影颜色的透明度来调试，试试。感谢你的支持

**Comment by ymwm-lxl** [comment]
我又回到了这里导致这个话题重新打开，是因为在新的场景中我发现这个问题依旧存在。
我尝试设置了 app:hl_shadowColor="#ffffbf00" ，当扩散范围 4dp 的时候，显示效果依然是淡淡的，不能够满足 UI 设计图纸中的显示效果。很明显的能够看到阴影开始的地方的色值就是淡化的，而并不是真实的、明确的从我在 xml 中设置的 #ffffbf00 开始扩散的。
------------
发现作者在这段期间又更新了多个版本，为作者的勤奋点赞。

**Comment by lsCoding666** [comment]
这个问题解决了吗 最新版本3.4.0还是有问题 颜色已经设置#ff0000ff了，limit 也设置的很大，但是仍然阴影就是一条蓝色的细线。

ShadowLayout shadowLayout = baseViewHolder.getView(R.id.shadowLayout);
            shadowLayout.setShadowColor(getContext().getResources().getColor(R.color.blue));//#ff0000ff
            shadowLayout.setShadowLimit(ScreenUtil.dip2px(10f));

**Comment by lsCoding666** [comment]
我知道了 这里确实有个bug，是因为如果设置了ff0000ff这样的话 程序会认为没有设置透明色，从而加上了16%的透明度，所以看起来很淡。

如果把颜色改为fe0000ff的话 颜色就很明显了@lihangleo2
