### ISSUE TITLE
迁移AndroidX以后，发现RecyclerView的item中被阴影包裹的部分点击事件失效了

### ISSUE THREAD

**Issue by linzengjie** [lihangleo2/ShadowLayout#55]
红框部分为item布局，顶部的时间区域可以响应条目点击事件，其他被阴影包裹的区域无法响应条目点击事件
<img width="377" alt="WX20200902-154727@2x" src="https://user-images.githubusercontent.com/24429005/91961804-446d7200-ed3e-11ea-8683-fd8b99e00790.png">

**Comment by lihangleo2** [comment]
嗯   这里确实会有问题。因为加上了shape功能后。目前解决的方式是  用shadowLayout里的子view做点击处理。 感谢你的支持  我会找时间解决。
