### ISSUE TITLE
佬,又发现了几个错别字.

### ISSUE THREAD

**Issue by lydlovezjr** [lihangleo2/ShadowLayout#57]
<img width="690" alt="微信截图_20200908182223" src="https://user-images.githubusercontent.com/19246347/92465016-990e6280-f200-11ea-9d27-9f34b9a6e5c6.png">

**Comment by lydlovezjr** [comment]
![360截图20200908183058227](https://user-images.githubusercontent.com/19246347/92465798-ab3cd080-f201-11ea-8f46-fe85ab033ed3.jpg)
![360截图20200908183123496](https://user-images.githubusercontent.com/19246347/92465801-ac6dfd80-f201-11ea-99b4-701e693e4c01.jpg)

**Comment by lydlovezjr** [comment]
colord这个拼写错误,应该出现有三处.

**Comment by lihangleo2** [comment]
哈哈哈  好的好的 不严谨了。有时间去改掉 。谢谢你

**Comment by lydlovezjr** [comment]
客气了,佬
