### ISSUE TITLE
setmShadowColor

### ISSUE THREAD

**Issue by SimonZL** [lihangleo2/ShadowLayout#58]
setmShadowColor  代码设置后  阴影颜色变成黑色的阴影了

**Comment by lihangleo2** [comment]
demo中设置动态设置颜色是没有问题的。你那是在什么时候设置的颜色呢

**Comment by lihangleo2** [comment]
issue保留半个月，如果看到请尽快联系啊我。非常感谢你的支持~

**Comment by lihangleo2** [comment]
因为你暂未回复我。已过去10来天。如果看到了 请回复我并重新打开这个issues
