### ISSUE TITLE
建议作者增加设置渐变色的方法

### ISSUE THREAD

**Issue by jiqianwen** [lihangleo2/ShadowLayout#59]
跪求

**Comment by lihangleo2** [comment]
你的意思是添加 阴影渐变色  还是填充渐变色？

**Comment by jiqianwen** [comment]
> 你的意思是添加 阴影渐变色 还是填充渐变色？

填充渐变色，阴影的渐变色一般很少会有这种需求吧- -

**Comment by lcyluo** [comment]
我也遇到这样的问题，设置shape背景，然后直接crash了

**Comment by lihangleo2** [comment]
嗯，后续我会改掉的。之前为了不必要的麻烦，在设置drawable的时候，正常背景和点击true的背景，对象类型要保持一致。感谢你们的支持，抽空我会更新的。

**Comment by dapanjimianpaigumian** [comment]
> 跪求

+1

**Comment by lihangleo2** [comment]
功能已经加上，可以下载最新demo3.1.0。感受下
