### ISSUE TITLE
为什么我套上去之后，阴影范围很大，我hl_shadowLimit设置的是5

### ISSUE THREAD

**Issue by Zaylour** [lihangleo2/ShadowLayout#6]
[]
![image](https://user-images.githubusercontent.com/31010597/63008290-e52f8c00-beb4-11e9-95b3-ecf05daf7629.png)
(url)

[
![image](https://user-images.githubusercontent.com/31010597/63008309-f5e00200-beb4-11e9-9e68-75e7d295e6e4.png)
](url)

**Comment by lihangleo2** [comment]
你把RelativeLayout里的margin全部去掉啊。要知道ShadowLayout是个布局。除了阴影功能外，其实就是个FramLayout是
