### ISSUE TITLE
能否支持setClipToOutline设置圆角 view

### ISSUE THREAD

**Issue by YuYongzhi** [lihangleo2/ShadowLayout#60]
当 ShadowLayout 设置了 hl_cornerRadius，但内部子 view 有背景时，不能达到圆角的目的
![image](https://user-images.githubusercontent.com/6104276/95838372-46324880-0d74-11eb-83bb-3ed90a56ac41.png)

期待结果：
![image](https://user-images.githubusercontent.com/6104276/95838413-521e0a80-0d74-11eb-86a0-a85c11d2d0f3.png)

**Comment by lihangleo2** [comment]
要达到这个效果，demo中已经有效果展示了。在你使用shadowlayout的时候，如果你设置了子view的背景，会把shadowLayout盖住，这个时候不止盖住圆角，连背景也会盖住。api中也完全诠释了该怎么用。作者不用因为个人小角度，去改整体设计。感谢你的支持
