### ISSUE TITLE
点击事件问题

### ISSUE THREAD

**Issue by 13253863229** [lihangleo2/ShadowLayout#62]
ShadowLayout作为RecyclerView的item布局，此时ShadowLayout设置点击效果后(hl_layoutBackground_true="xxxxx")，ViewHolder的itemView点击事件被屏蔽了，只响应ShadowLayout的点击效果。去掉ShadowLayout的点击效果或者设置app:clickable="false"，恢复ViewHolder的itemView点击事件。

**Comment by lihangleo2** [comment]
因为ShadowLayout要监听手势状态才能实现shape功能，这个时候已经消费了点击事件。如果ShadowLayout不是recyclerView里item的根目录，这个时候是会消费事件，事件传递不到他下面的view。假如此时ShadowLayout已经处于根目录，一切都是正常的。感谢你的问题
