### ISSUE TITLE
可以把glide的依赖抽离出来吗？

### ISSUE THREAD

**Issue by lwei1992** [lihangleo2/ShadowLayout#63]
我是之前用的是2版本的，想升级到你的3版本，发现爆了好多好多红，原因是你3版本依赖的是glide4.9，我项目有环信那些东西，他们依赖的3.7的glide，现在想升级就很麻烦了

**Comment by lihangleo2** [comment]
并不会是因为这个报错。 3.0后更新了大量api。2.0升级到3.0要慎重。并不是因为glide的版本导致的

**Comment by lihangleo2** [comment]
你那里报了glide的错吗？应该是警告吧？

**Comment by lihangleo2** [comment]
据我studio4.0测试，版本会使用你依赖中最新的。 如果确实不是因为ShadowLayou，是因为版本冲突的话可以看看https://blog.csdn.net/sinat_31490099/article/details/88059048统一版本。如果有问题，再打开这个issues

**Comment by lihangleo2** [comment]
module里使用的是implementation依赖。意思是glide只在module下使用。在你依赖ShadowLayout后，主项目是根本不可能拿到我所依赖的glide的。但项目里2个glide工具类  确实暴露了出来，稍后我会修改的。

**Comment by lwei1992** [comment]
好的老哥，奥利给！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "leo"<notifications@github.com&gt;; 
发送时间: 2020年11月6日(星期五) 下午2:19
收件人: "lihangleo2/ShadowLayout"<ShadowLayout@noreply.github.com&gt;; 
抄送: "^(**)^"<289501937@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [lihangleo2/ShadowLayout] 可以把glide的依赖抽离出来吗？ (#63)





 
module里使用的是implementation依赖。意思是glide只在module下使用。在你依赖ShadowLayout后，主项目是根本不可能拿到我所依赖的glide的。但项目里2个glide工具类  确实暴露了出来，稍后我会修改的。
