### ISSUE TITLE
绑定textview设置字体颜色，点击和松开字体会变化，但是如果设置了app:clickable属性，字体颜色不会变化

### ISSUE THREAD

**Issue by jiqianwen** [lihangleo2/ShadowLayout#65]
还有一个需求，按钮可点击并且松开状态的时候有阴影，禁用或者点击之后去掉阴影或者设置阴影为另一种颜色。申请加群了，没人通过，只能提Issues了，尴尬。

**Comment by lihangleo2** [comment]
ShadowLayout的阴影颜色是支持动态 代码设置的。可以任意修改你的阴影颜色
