### ISSUE TITLE
阴影内部的间距问题

### ISSUE THREAD

**Issue by zhupengxiang** [lihangleo2/ShadowLayout#66]
阴影内部的margin  我想实现图一的效果
![image](https://user-images.githubusercontent.com/17894209/97836391-2fe62f80-1d17-11eb-8f6c-64ebc07e074e.png)
但是现在加完hl_shadowLimit后 成图二的效果了
![image](https://user-images.githubusercontent.com/17894209/97836468-599f5680-1d17-11eb-9f69-ca0353ca7602.png)

**Comment by lihangleo2** [comment]
你把左右2边阴影隐藏试试。用属性hl_shadowHiddenLeft =“true”；hl_shadowHiddenRight="true"

**Comment by zhupengxiang** [comment]
这样倒是可以了   楼主有qq吗  加个咨询问题

**Comment by lihangleo2** [comment]
可以加那个群。群里除了探讨这个库的问题 也可以探讨其他Android问题
