### ISSUE TITLE
xml的 属性能动态设置吗

### ISSUE THREAD

**Issue by Sunshine-Joex** [lihangleo2/ShadowLayout#67]
您好！这两个属性，能不能代码动态设置
app:hl_layoutBackground="@color/color_fffce1"
app:hl_strokeColor="@color/color_ff1a1a"

**Comment by lihangleo2** [comment]
后续会加上动态设置

**Comment by lihangleo2** [comment]
已经更新到了3.1.3。可以看看新的api，有方法介绍
