### ISSUE TITLE
单边阴影有问题

### ISSUE THREAD

**Issue by LLQQHH** [lihangleo2/ShadowLayout#69]
<com.lihang.ShadowLayout
        android:id="@+id/mShadowLayout"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center_horizontal"
        app:hl_cornerRadius="0dp"
        app:hl_shadowColor="#cc000000"
        app:hl_shadowHiddenLeft="true"
        app:hl_shadowHiddenRight="true"
        app:hl_shadowHiddenTop="true"
        app:hl_shadowLimit="10dp"
        >
        <TextView
            android:id="@+id/txt_test"
            android:layout_width="wrap_content"
            android:layout_height="36dp"
            android:gravity="center"
            android:paddingLeft="10dp"
            android:paddingRight="10dp"
            android:text="圆角"
            android:textColor="#000" />
    </com.lihang.ShadowLayout>
默认不应该重上往下，由黑慢慢变白吗，这个代码会出现阴影中间很黑，旁白很白，
![QQ截图20201111153415](https://user-images.githubusercontent.com/19651932/98782687-661c6100-2433-11eb-9f5a-6726dcb12ac6.png)

**Comment by lihangleo2** [comment]
当使用单边阴影的时候，确实会存在这样的问题。 正常逻辑的阴影是周边围绕。隐藏单边的时候 其实阴影没有变，只是单边把它覆盖了造成了这样的问题。我也在找最佳的解决方案。目前的解决方案是调整好阴影透明度和shadowLimit也能达到很理想的效果。比如demo里的title一样

**Comment by lihangleo2** [comment]
嗯，确实会存在这样的问题。感谢你的支持！有时间我会修复的

**Comment by lihangleo2** [comment]
已经修复，将会发布3.1.4版本
