### ISSUE TITLE
无法在recylerView中自定阴影颜色

### ISSUE THREAD

**Issue by hongguangqq** [lihangleo2/ShadowLayout#7]
在设置阴影或者圆角时，控件会获取宽高进行设置，但此时recycleView中的控件的宽高是0，会报错

**Comment by lihangleo2** [comment]
https://juejin.im/post/5d4c1392f265da03bc126584#heading-12请看这篇文章！

**Comment by lihangleo2** [comment]
https://juejin.im/post/5d4c1392f265da03bc126584#heading-12
