### ISSUE TITLE
某些特殊场景下createShadowLayout报错

### ISSUE THREAD

**Issue by tjgo** [lihangleo2/ShadowLayout#70]
大佬好 Orz
ShadowLayout.java:566-567做了如下的操作

shadowWidth = shadowWidth / 4;
shadowHeight = shadowHeight / 4;

随后直接使用上述width和height进行了createBitmap操作。

传入shadowWidth和shadowHeight的值介于1-3之间，会导致处理过的width和height为0，在createBitmap的时候引起报错。

ver 3.0.3

**Comment by tjgo** [comment]
（ver 3.0.3

**Comment by lihangleo2** [comment]
好的。谢谢你的测试。我会完善的
