### ISSUE TITLE
ShadowLayout 点击事件无法响应

### ISSUE THREAD

**Issue by cdalwyn** [lihangleo2/ShadowLayout#72]
我尝试使用ShadowLayout封装一个通用的自定义卡片布局，但发现点击事件无法响应，我只能采取方案：将ShadowLayout挪出来，在每一个子布局里再引入Shadowlayout，希望尽快解决该问题。
![福昕截屏20201120144454960](https://user-images.githubusercontent.com/46589715/99767977-057dda00-2b3f-11eb-9f12-27d7feaa4d6a.PNG)

**Comment by lihangleo2** [comment]
是这样的。比如你的ShadLayout里的子view设置了点击事件以后  是会覆盖到ShadowLayout的点击事件的。
