### ISSUE TITLE
单独设置上下左右的hl_shadowLimit

### ISSUE THREAD

**Issue by protectedMan** [lihangleo2/ShadowLayout#73]
在列表中使用ShadowLayout ,可能上下左右有不一样的需求

**Comment by lihangleo2** [comment]
请仔细阅读文档。根据shadowLimit和 阴影x轴偏移量 和y轴偏移量，可以达到你说的效果

**Comment by protectedMan** [comment]
需要阴影偏移量不变,只改变扩散区域. 左右要求的扩散区域和上下要求的扩散区域不同.
