### ISSUE TITLE
用selector做tabbar，立马启动设置select = true，偶发不生效

### ISSUE THREAD

**Issue by CharlinFeng** [lihangleo2/ShadowLayout#77]
三个tab，第一个启动后立马设置状态为选中。

有一定概率（原因未知），无法选中，但页面加载完成后，点击切换完全正常，就是启动瞬间设置一会有效一会无效。

**Comment by CharlinFeng** [comment]
比如首页，我的两个tab。
app启动首页的图片是选中的才对（代码设置为选中）。
10次启动有1次或2次选中图片效果无效。

**Comment by lihangleo2** [comment]
这个问题我之前也测试出来了。但是改过2个版本之后  经测试。已经修复了的  你用嘚瑟最新的3.1.6版本吗

**Comment by CharlinFeng** [comment]
可能和版本有关，我改了试试。

另外，你可不可以加一个ios里面的那种默认选中，不然我还要写代码。

上面的tab的首页，一启动肯定是选中状态的。给个自定义属性，可以默认选中或禁用

**Comment by CharlinFeng** [comment]
还有一个需求，你做的这个感觉还可以集成一个子功能，
就是ios里面的visualBlur 模糊效果，理论上这个也属于你的功能集合。

赞

**Comment by lihangleo2** [comment]
有默认选中的。你在xml里直接设置select="true"。试试

**Comment by lihangleo2** [comment]
好的 。毛玻璃效果我研究一下
