### ISSUE TITLE
透明度提高之后，边缘阴影过度不平滑。感觉很割裂。

### ISSUE THREAD

**Issue by zhoujia456888** [lihangleo2/ShadowLayout#79]
如图。我设置颜色为app:hl_shadowColor="#80162F4E"。扩散大小为app:hl_shadowLimit="10dp"。组件边缘会有明显的切割痕迹
![image](https://user-images.githubusercontent.com/7905253/102450250-f2dcbf00-4070-11eb-93df-ece7ab4e37f9.png)

这张更明显了，阴影部分完全就是一个方块
![image](https://user-images.githubusercontent.com/7905253/102450413-46e7a380-4071-11eb-9236-cd9c73ddb8d1.png)
![image](https://user-images.githubusercontent.com/7905253/102450440-5961dd00-4071-11eb-9ebb-e1e722117ea2.png)

**Comment by lihangleo2** [comment]
兄弟，你的图片我看不到。麻烦可以私聊我吗?qq:445442684

**Comment by libern** [comment]
> 兄弟，你的图片我看不到。麻烦可以私聊我吗?qq:445442684

图片要翻墙才能看到

**Comment by lihangleo2** [comment]
在最新版本3.1.8已修复
