### ISSUE TITLE
存在过渡绘制问题

### ISSUE THREAD

**Issue by Edgar-Dong** [lihangleo2/ShadowLayout#8]
1、RecycleView中item存在过渡绘制问题；
2、RecycleView中数据比较多时连续滑动会出现卡顿现象，打开开发者模式中的GPU呈现模式分析连续滑动列表发现有绘制时间过长问题；
还请楼主确认是否存在如上两个问题。

**Comment by lihangleo2** [comment]
https://juejin.im/post/5d4c1392f265da03bc126584#heading-12  可以看看这个链接
