### ISSUE TITLE
加了这个开源项目，每次gradle时间变长

### ISSUE THREAD

**Issue by candebbs** [lihangleo2/ShadowLayout#82]
在我的androidx项目，通过
    implementation 'com.github.lihangleo2:ShadowLayout:3.1.6'
每次gradle时间，会变长差不多一分钟，请问怎样解决？

**Comment by lihangleo2** [comment]
可能是因为ShadowLayout是在support下的library。在androidx项目里，需要转移成androidx项目。但这并不会影响使用。感谢你的支持

**Comment by gs666** [comment]
这个项目核心文件就一个类：ShadowLayout
完全可以直接复制粘贴用于项目，就不会有编译的问题了
