### ISSUE TITLE
阴影异常

### ISSUE THREAD

**Issue by twirain** [lihangleo2/ShadowLayout#83]
版本：3.1.8

<com.lihang.ShadowLayout
            android:id="@+id/add_city"
            android:layout_width="0pt"
            android:layout_height="100pt"
            android:onClick="@{clickHandler::onClick}"
            android:layout_marginHorizontal="26pt"
            android:layout_marginBottom="58pt"
            app:hl_angle="270"
            app:hl_cornerRadius="44pt"
            app:hl_endColor="@color/theme_gradient_end_color"
            app:hl_shadowColor="@color/theme_shadow_color"
            app:hl_shadowHiddenTop="true"
            app:hl_shadowLimit="12pt"
            app:hl_startColor="@color/theme_gradient_start_color"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent">

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="center"
                android:drawablePadding="12pt"
                android:text="@string/text_add_city"
                android:textColor="@color/white"
                android:textSize="32pt"
                app:drawableStartCompat="@drawable/icon_add" />
        </com.lihang.ShadowLayout>

隐藏了顶部阴影后，阴影显示异常

**Comment by lihangleo2** [comment]
android:layout_width="0pt"

**Comment by twirain** [comment]
0pt在约束布局下的，这个没问题
