### ISSUE TITLE
设置阴影后，阴影下面为什么是白色的

### ISSUE THREAD

**Issue by jerry9433** [lihangleo2/ShadowLayout#85]
如图，请问阴影下面的背景色是白色的，不能像cardView一样是透明色的吗？
![image](https://user-images.githubusercontent.com/31622465/103858813-f7d2e280-50f3-11eb-8e12-e20f7b475cfa.png)

**Comment by lihangleo2** [comment]
你发的图我看不了。能否加我QQ联系我。非常感谢。

**Comment by lihangleo2** [comment]
已解决，直接设置marginTop="-limitdp"。limit就是你阴影limit的值
