### ISSUE TITLE
考虑添加圆角裁剪功能吗？

### ISSUE THREAD

**Issue by 1420965446** [lihangleo2/ShadowLayout#87]
如题，子View 超出 shadowLayout 时被裁剪

**Comment by lihangleo2** [comment]
目前不规则的圆角不好处理。等有好方案了 再解决

**Comment by lihangleo2** [comment]
已解决。稍后会发布3.2.0版本。

**Comment by 1420965446** [comment]
emmm, 辛苦了。 希望能再顺手加一个开关（**默认关**，这样不会影响到之前的使用者），鉴于其他开发者可能 并不需要裁减
