### ISSUE TITLE
选中不选中，默认选中还是不好使

### ISSUE THREAD

**Issue by CharlinFeng** [lihangleo2/ShadowLayout#88]
<com.zhilian.kelun.App.VM.VMShadowLayout
                    android:id="@+id/sellayout"
                    android:layout_marginLeft="10dp"
                    app:hl_layoutBackground="@drawable/weixuanzhong"
                    app:hl_layoutBackground_true="@drawable/xuanzhong"
                    app:hl_shapeMode="selected"
                    select="true"
                    android:layout_width="22dp"
                    android:layout_height="22dp">

1. 默认选中没效果
2. 我要点一下，突然发现他选中了。
3. 我用代码设置selected = true，一样不好使

**Comment by CharlinFeng** [comment]
另外我发现你的demo中，也没有关于默认选中的代码。

**Comment by lihangleo2** [comment]
嗯。之前是有问题的 请确保你使用的是最新版本。  默认选择其实和系统一样的。直接在xml里设置selected="true"。当然也可以在onCreate里使用setSelect（true）。
