### ISSUE TITLE
设置app:clickable="false" 的时候，app:hl_endColor，app:hl_startColor渐变失效

### ISSUE THREAD

**Issue by zhoujia456888** [lihangleo2/ShadowLayout#89]
我想把ShadowLayout当做一个渐变的view的时候，设置app:clickable="false"，渐变颜色就变成白色了。设置hl_layoutBackground_clickFalse虽然有了颜色，但是就没渐变了。
是否有方法可以同时有渐变和不可点击？

我看代码里面 设置渐变有这一段。。。。
`
if (!isClickable) {
            paint.setShader(null);
            return;
        }
`

**Comment by lihangleo2** [comment]
这个东西要灵活运用。ShadowLayout只是提供了一个app:clickable="false"时，一个默认不可点击的颜色值，会替换掉所有的正常状态；如果你不想他点击，但是又想保持着渐变色。那么你只能在代码里，给一个flag。比如给他设置一个tag,setTag("0")，如果是“0”的话，就不让他触发他的点击逻辑。在这里ShadowLayout不会因为谁的个人功能，去改变他原本的api。非常感谢
