### ISSUE TITLE
好像默认会给一些padding来显示阴影，那么在list里面，就很难把这个padding去掉了，有办法在layout的外部渲染吗？

### ISSUE THREAD

**Issue by libern** [lihangleo2/ShadowLayout#90]
好像默认会给一些padding来显示阴影，那么在list里面，就很难把这个padding去掉了，有办法在layout的外部渲染吗？

**Comment by libern** [comment]
就是同时用LinearLayout放垂直的5个没有设置任何padding和margin的这个layout，那么这几个layout之间不是贴着的，而有一些空隙，比较影响布局

**Comment by lihangleo2** [comment]
是这样的  如果你需要阴影的话是有间距的。像你这么描述是不需要阴影的情况，那么你直接可以设置阴影不可见。就行咯
