### ISSUE TITLE
ShadowLayout的渐变是线性渐变，可否考虑加入径向渐变

### ISSUE THREAD

**Issue by zhangjianzhu** [lihangleo2/ShadowLayout#94]
例如：
android:type：
"linear" | 线性渐变.可以理解为 y=kx+b.
"radial" | A radial gradient.圆形渐变，起始颜色从cenralX,centralY点开始。
"sweep" | A sweeping line gradient.

<gradient
        android:centerX="0.5"
        android:centerY="0.0"
        android:endColor="#0EEEFF"
        android:gradientRadius="360"
        android:startColor="#2D5EFF"
        android:type="radial" />

![image](https://user-images.githubusercontent.com/18592113/113137247-dd258b00-9256-11eb-9a45-f16ef5a2718b.png)

**Comment by lihangleo2** [comment]
当然可以考虑，等空下来了会更新的

**Comment by lihangleo2** [comment]
深思熟虑后，加上RadialGradient，SweepGradient虽然不难，但是由于可考虑的参数太多，会让ShadowLayout很臃肿，难用。且在普遍开发场景里，这种场景较少。建议自己用shape搞定，如果需要阴影，在嵌套一层ShadowLayout。感谢你的提议
