### ISSUE TITLE
圆角加单边的情况下，圆角部分的阴影不显示

### ISSUE THREAD

**Issue by Janky-Young** [lihangleo2/ShadowLayout#95]
作者你好，如题，我使用该库的时候发现在圆角加单边的情况下，圆角部分的阴影不显示，目前版本能否解决这个问题呢

**Comment by lihangleo2** [comment]
什么意思，是隐藏其他3边阴影的情况吗?

**Comment by lihangleo2** [comment]
什么意思，是隐藏其他3边阴影的情况吗?

**Comment by Janky-Young** [comment]
> 什么意思，是隐藏其他3边阴影的情况吗?

是的，例如隐藏上、左、右，只保留下边，然后圆角部分就没有阴影了

**Comment by lihangleo2** [comment]
在demo中,使用的标题栏就是隐藏3边的。因为是直角不会出现这样的问题。如果不是直角的话，那么阴影就和圆角大小，还有阴影扩散区域有关；比如扩散区域是10dp,圆角是10dp。用最简单的话来说，就是阴影其实和原view一样大小和角度，我的操作是把原图缩小了扩散区域的大小就能看见阴影，但是阴影的渐变扩散区域是10dp，所以这不可见区域无法去掌控，一旦角度够大且扩散区域够大的时候，就会出现原view覆盖阴影，且这个可视区域无法掌控。最佳的解决方案是 你可以根据阴影的偏移量，去对阴影调试，经实践，是能达到比较良好的效果的。希望对你有帮助，感谢你的支持！~

**Comment by lihangleo2** [comment]
在demo中,使用的标题栏就是隐藏3边的。因为是直角不会出现这样的问题。如果不是直角的话，那么阴影就和圆角大小，还有阴影扩散区域有关；比如扩散区域是10dp,圆角是10dp。用最简单的话来说，就是阴影其实和原view一样大小和角度，我的操作是把原图缩小了扩散区域的大小就能看见阴影，但是阴影的渐变扩散区域是10dp，所以这不可见区域无法去掌控，一旦角度够大且扩散区域够大的时候，就会出现原view覆盖阴影，且这个可视区域无法掌控。最佳的解决方案是 你可以根据阴影的偏移量，去对阴影调试，经实践，是能达到比较良好的效果的。希望对你有帮助，感谢你的支持！~
