### ISSUE TITLE
除去多余的背景色。

### ISSUE THREAD

**Issue by qflbai** [lihangleo2/ShadowLayout#96]
![微信截图_20210410165154](https://user-images.githubusercontent.com/23705172/114264388-3773d800-9a1d-11eb-9850-d19c28ba9cee.png)
阴影上边多了一部分背景色，怎么除去多余的背景色。

**Comment by lihangleo2** [comment]
shadowLayout有默认的背景色，你将背景色设置全透明即可

**Comment by qflbai** [comment]
![微信图片_20210413161753](https://user-images.githubusercontent.com/23705172/114521272-d9413200-9c74-11eb-892c-23e8210c2c54.jpg)
![微信截图_20210413161930](https://user-images.githubusercontent.com/23705172/114521276-da725f00-9c74-11eb-915a-94f00e0bbde8.png)
![1618302106(1)](https://user-images.githubusercontent.com/23705172/114521282-dc3c2280-9c74-11eb-90ac-2ab0720ad910.png)

背景设置为透明，阴影过渡完，依然存在一段白色背景

**Comment by wuzhongyuan** [comment]
解决了没有？，ShadowLayout设置背景透明确实没用

**Comment by w1984908499** [comment]
请问解决了吗
