### ISSUE TITLE
边框被遮挡

### ISSUE THREAD

**Issue by AndyGu** [lihangleo2/ShadowLayout#97]
1.ShadowLayout中包含一个match_parent的ImageView
2.给ShadowLayout设置了stroke相关属性
3.ImageView加载图片会遮挡stroke，但是设置padding又会使ImageView显示出问题【因为有圆角】
请问下有没有合适的解决方法，还是我使用的有问题？

**Comment by lihangleo2** [comment]
你使用的没有问题。shadowlayout从开始设计初，就不是为了圆角图片设计的，所以这方面是没有考虑的。如果你说用最简单的方式解决的话，那么在你的这层view外再嵌套一层 ，放一个stroke样式的shape。后续有时间，基于shadowLayout的设计我看能不能加上这功能。感谢你的支持

**Comment by lihangleo2** [comment]
很遗憾的告诉你。基于ShadowLayout的设计初心。这里是针对所有的view控件右剪裁效果。不像某些库是单独为image设计，比如RoundImageView。也经过思考，决定还是不加上此功能。最简单的方式是，你直接使用第三方圆角imageView的库，需要阴影的话嵌套一层ShadowLayout。感谢你的支持！~

**Comment by AndyGu** [comment]
好的，感谢
