### ISSUE TITLE
是否可以增加左边上边设置一种颜色，右边下边设置另外一种颜色？？？

### ISSUE THREAD

**Issue by wangshanhai** [lihangleo2/ShadowLayout#98]
是否可以增加左边上边设置一种颜色，右边下边设置另外一种颜色？？？

**Comment by wangshanhai** [comment]
![image](https://user-images.githubusercontent.com/19216088/115350559-d51e9280-a1e7-11eb-8644-61fe26460e7d.png)

**Comment by lihangleo2** [comment]
兄弟，你这个属于你本身功能的特定需求。ShadowLayout不会因为个别功能去改变它自身的定位和初衷的、个人觉的你如果要用ShadowLayout实现这一功能。可以用2个ShadowLayout一个白色阴影一个黑色阴影 然后通过偏移量去勉强实现你截图上的功能。
